name: tweethistory
description: "Twitter archive viewer and organizer"
publish_to: 'none' # プライベートパッケージとして管理

# アプリケーションのバージョン情報
# iOS: CFBundleShortVersionString, Windows: product version
version: 0.3.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.1.9
  intl: ^0.20.2
  idb_shim: 2.6.6
  idb_sqflite: ^1.3.5
  sqflite_common_ffi: ^2.3.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  shared_preferences: ^2.2.2
  result_dart: ^2.1.1
  web: ^1.1.1
  package_info_plus: ^8.0.4
  url_launcher: ^6.2.5
  langchain_ollama: ^0.3.3
  langchain: ^0.7.8
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0 # 推奨リント設定
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  build_runner: ^2.4.15
  freezed: ^2.5.7
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true # 国際化対応
  
  assets:
    - assets/icons/
